# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
  
  
   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
   
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
          submodules: recursive
          token: ${{ secrets.CI_SECRET }}

    - name: Install contract dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf libc6-dev-riscv64-cross libc6-riscv64-cross linux-libc-dev-riscv64-cross
        wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 18 && rm llvm.sh
        cargo install cargo-generate
        rustup target add riscv64imac-unknown-none-elf

    - name: Create Symlink
      run: sudo ln -s /usr/riscv64-linux-gnu/include/gnu/stubs-lp64d.h /usr/riscv64-linux-gnu/include/gnu/stubs-lp64.h

    - name: Start devnet in background
      env:
        RUSTFLAGS: "-C linker=rust-lld"
        CARGO_TARGET_RISCV64IMAC_UNKNOWN_NONE_ELF_LINKER: rust-lld
        CC_riscv64imac_unknown_none_elf: riscv64-unknown-elf-gcc
        AR_riscv64imac_unknown_none_elf: riscv64-unknown-elf-ar
        C_INCLUDE_PATH: /usr/riscv64-linux-gnu/include
        CFLAGS: "-I/usr/riscv64-linux-gnu/include"
        TARGET_CFLAGS: "-I/usr/riscv64-linux-gnu/include"
      run: |
          sudo apt-get update
          sudo apt-get install -y jq sed gawk tmux tmuxp expect make
          curl -LO https://github.com/nervosnetwork/ckb/releases/download/v0.201.0/ckb_v0.201.0_x86_64-unknown-linux-gnu.tar.gz
          tar -xzf ckb_v0.201.0_x86_64-unknown-linux-gnu.tar.gz
          sudo cp ckb_v0.201.0_x86_64-unknown-linux-gnu/ckb /usr/local/bin/
          curl -LO https://github.com/nervosnetwork/ckb-cli/releases/download/v1.4.0/ckb-cli_v1.4.0_x86_64-unknown-linux-gnu.tar.gz
          curl -LO https://github.com/nervosnetwork/ckb-cli/releases/download/v1.13.0/ckb-cli_v1.13.0_x86_64-unknown-linux-gnu.tar.gz
          tar -xzf ckb-cli_v1.13.0_x86_64-unknown-linux-gnu.tar.gz
          sudo cp ckb-cli_v1.13.0_x86_64-unknown-linux-gnu/ckb-cli /usr/local/bin/
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
          sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

          git submodule update --init --recursive
          cd ./testnet/devnet
          chmod +x setup-devnet.sh print_accounts.sh deploy_contracts.sh sudt_helper.sh 
          ./setup-devnet.sh
          ckb run > /dev/null 2>&1 &
          sleep 3
          ckb miner > /dev/null 2>&1 &
          sleep 3
          ./print_accounts.sh
          sleep 6
          expect fund_accounts.expect
          sleep 10
          ./deploy_contracts.sh
          sleep 15
          ./sudt_helper.sh fund
          sleep 10
          ./sudt_helper.sh balances
          cd ../..
    
    - name: Wait for devnet to initialize
      run: sleep 30

    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Race
      run: go test -v -race ./...
